
// Mixed Message Generator


/* Messages - Generated by Google's Bard */

// Jokes
const jokes = ['Knock knock. Who\'s there? Interrupting cow. Interrupting cow wh--, MOOOOOO!',
                        'What do you call a fish with no eyes? Fsh!',
                        'Why did the scarecrow win an award? Because he was outstanding in his field.'];

// Inspirational Quotes
const inspirationalQuotes = ['18th Century: "The only thing necessary for the triumph of evil is for good men to do nothing." - Edmund Burke',
                                     '19th Century: "The greatest glory in living lies not in never falling, but in rising every time we fall." - Nelson Mandela',
                                     '20th Century: "The only way to do great work is to love what you do. If you haven\'t found it yet, keep looking. Don\'t settle." - Steve Jobs'];

// Random Facts
const randomFacts = ['Animal Fact: A group of jellyfish is called a "bloom".',
                             'Space Fact: The sun makes up 99.8% of the mass of the solar system.',
                             'The first car was invented in 1886 by Karl Benz.'];

// Haiku
const haiku = ['Spring Haiku: Blossoms burst forth --- From the cold, dark winter ground --- Nature awakens',
                       'Summer Haiku: Sunlight warms the skin --- As birds sing in the trees --- A time for joy',
                       'Autumn Haiku: Leaves change color -- The air grows crisp and cool -- A time for reflection'];



/* Program Code */
console.log('Welcome to the MessageGenerator3000..\n');

setTimeout(() => {
    console.log("There are currently four options to choose from..");
}, 1000);

setTimeout(() => {
    console.log("Jokes(1) | Inspirational Quotes(2) | Random Facts(3) | Haiku's(4)");
}, 2000);
setTimeout(() => {
    console.log("..with each category containing 3 preset messages.\n");
}, 3000);


// Take input
const readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
});


const googleBard = () => {
    console.log('**All messages were generated by Google\'s Bard**');
}
const categorySelected = (name) => {
    if (name === '1') {
        console.log(`\nCategory Selected: Jokes\n` + jokes[Math.floor(Math.random()*3)]);
        googleBard();
        readline.close();
    } else if (name === '2') {
        console.log(`\nCategory Selected: Inspirational Quotes\n` + inspirationalQuotes[Math.floor(Math.random()*3)]);
        googleBard();
        readline.close();
    } else if (name === '3') {
        console.log(`\nCategory Selected: Random Facts\n` + randomFacts[Math.floor(Math.random()*3)]);
        googleBard();
        readline.close();
    } else if (name === '4') {
        console.log(`\nCategory Selected: Haiku's\n` + haiku[Math.floor(Math.random()*3)]);
        googleBard();
        readline.close();
    }
};


setTimeout( () => {
    readline.question('Select a category based off its Category Number [1,2,3,4]:', name => {
        const indexes = ['1','2','3','4'];
        if (indexes.includes(name)) {
            categorySelected(name)
        } else {
            readline.question('Invalid Entry! Select a category based off its Category Number [1,2,3,4]:', name => {
                if (indexes.includes(name)) {
                    categorySelected(name);
                } else {
                    console.log('\nInvalid Entry! **MessageGenerator3000 will shut down after one more incorrect entry**');
                    readline.question('Invalid Entry! Select a category based off its Category Number [1,2,3,4]:', name => {
                        if (!indexes.includes(name)) {
                            console.log('Invalid Entry! **MessageGenerator3000 shutting down**');
                            readline.close();
                        } else {
                            categorySelected(name)
                        }
                    });
                }
            });
        }
    });
}, 4000);




